/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vitali.koshel.ratesharing;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JFrame;

/**
 *
 * @author KoshelVR
 */
public class Settings extends javax.swing.JDialog {

    /**
     * Creates new form Settings
     */
    
    
    public Settings() {
        
        initComponents();
        jTextFieldsetPumpUnitName.setText(Main.tempName);
        if(Main.tempName.equals("SPM2250_4_inches")){
            jComboBoxPump.setSelectedIndex(1);
        }
        else {
            if(Main.tempName.equals("SPM2250_4.5_inches")){
                jComboBoxPump.setSelectedIndex(2);
            }
            else{jComboBoxPump.setSelectedIndex(0);}
        }
        jComboBoxtranstype.setSelectedIndex(Main.transtype);
        jComboBoxEngine.setSelectedIndex(Main.engineType);
        jTextFieldefficiency.setText(String.valueOf(Main.pumpEfficiency));
       //System.out.println("Main.transtype priletelo = ......"+Main.transtype); 
       //System.out.println("Main.enginetype priletelo = ......"+Main.engineType);
        //addWindowListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSetPumpUnitName = new javax.swing.JLabel();
        jTextFieldsetPumpUnitName = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPump = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxtranstype = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxEngine = new javax.swing.JComboBox<>();
        jLabelSetAll = new javax.swing.JLabel();
        jCheckBoxSetAll = new javax.swing.JCheckBox();
        jTextFieldefficiency = new javax.swing.JTextField();

        jLabelSetPumpUnitName.setText("Pump unit name:");

        jTextFieldsetPumpUnitName.setText("default");
        jTextFieldsetPumpUnitName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsetPumpUnitNameActionPerformed(evt);
            }
        });

        jButtonOK.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jLabel1.setText("Pump");

        jComboBoxPump.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "default", "SPM2250_4_inches", "SPM2250_4.5_inches" }));
        jComboBoxPump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPumpActionPerformed(evt);
            }
        });

        jLabel2.setText("Transmission");

        jComboBoxtranstype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "default", "Allison", "Caterpillar" }));

        jLabel3.setText("Engine");

        jComboBoxEngine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "default", "Detroit", "Caterpillar" }));
        jComboBoxEngine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBoxEngine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEngineActionPerformed(evt);
            }
        });

        jLabelSetAll.setText("SetALL");

        jTextFieldefficiency.setText("1.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSetPumpUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSetAll, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxSetAll, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxPump, 0, 136, Short.MAX_VALUE)
                            .addComponent(jTextFieldsetPumpUnitName)
                            .addComponent(jComboBoxtranstype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxEngine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldefficiency, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSetPumpUnitName)
                    .addComponent(jTextFieldsetPumpUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPump, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldefficiency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxtranstype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSetAll)
                    .addComponent(jCheckBoxSetAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jButtonOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
       //Передаем имя и тип НВД
        Main.tempName =jTextFieldsetPumpUnitName.getText();
        //Передаем тип двигателя
       Main.engineType=jComboBoxEngine.getSelectedIndex();
      // System.out.println("combobox dvigatel "+jComboBoxEngine.getSelectedIndex());
       //Передаем бит настроить все одинаково
       Main.setAllstate=jCheckBoxSetAll.isSelected();
       //Передаем тип коробки
       //System.out.println("OK button Main.transtype = ......"+Main.transtype);
       Main.transtype=jComboBoxtranstype.getSelectedIndex();
       //Коэффициент использования 
       Main.pumpEfficiency=Double.valueOf(jTextFieldefficiency.getText());
       //System.out.println("combobox poluchil "+jComboBoxtranstype.getSelectedIndex());
       //System.out.println("OK button Main.transtype = ......"+Main.transtype);
       dispose();
       
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jComboBoxPumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPumpActionPerformed
        jTextFieldsetPumpUnitName.setText(String.valueOf(jComboBoxPump.getSelectedItem()));
    }//GEN-LAST:event_jComboBoxPumpActionPerformed

    private void jComboBoxEngineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEngineActionPerformed
        Main.engineType=jComboBoxEngine.getSelectedIndex();
    }//GEN-LAST:event_jComboBoxEngineActionPerformed

    private void jTextFieldsetPumpUnitNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsetPumpUnitNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsetPumpUnitNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JCheckBox jCheckBoxSetAll;
    private javax.swing.JComboBox<String> jComboBoxEngine;
    private javax.swing.JComboBox<String> jComboBoxPump;
    private javax.swing.JComboBox<String> jComboBoxtranstype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelSetAll;
    private javax.swing.JLabel jLabelSetPumpUnitName;
    private javax.swing.JTextField jTextFieldefficiency;
    private javax.swing.JTextField jTextFieldsetPumpUnitName;
    // End of variables declaration//GEN-END:variables

    
}
